//export * from "./model/model";
//export * from "./model/meta";
//export * from "./match/ifmatch";
import * as BreakDown from "./match/breakdown";
export { BreakDown };
import * as Model from "./model/model";
export { Model };
import * as IFModel from "./match/ifmatch";
export { IFModel};
export * from "./match/breakdown";
export declare var bas: string;